---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCIiZNMNAFrOmDqGFCsnL1i90KEgR/iUkhcNid/XjRBiCQRMxZweDlrzzC6iJ82h/TL3aAp3zWQ89GZdpEAkhd+MsALKeENgmo9LsXgmFUU7FsVwYZVjyM+8MjIlUrPmMbjziHkQkF2qjoebnKpyOjzkZjmPf0troZnpj+j1odQHU2Blk0vo2tIrQGpmo5Sr78qwVHfokx4hBvIHq4wSR9/3gKIgZV0Xmro490DSDD3xiR1U5rVFTvmCtGu5g0SDxAqQKZbzHFf7RbpRTkNzKl1jpX8vE+Itq4K1HCdOftkpYb0yZ7t0Tt3Rl0crMunSCSBehSwHD3eMZcliGSKz9VTFmQe+vliEFGdThig2WwTRVjzeTsbDMzQs0/hs0mv0s79ly41/dXIu4LR2EIWfPTEJReTEWP+mEgX8/Wlx8hppzqEwEuc6215vOuJP6hKRCRXGWjaZiQqqelzCFYHDWpqzj0STiLN9AuMpgdl/gBKOnVg3xTflaSHPWFmWSQCvJ38dlNYKhD9Lgx89xqbMQ4deo6elLTy8hd63PCJeq4/1YfRcl95fWXYCPTCUqGmLRB5q6Twy1VKzoZhb66g2SrkON20DbvOf3bxhfw6PvpbrBdqo7Eaqbw/wAXDZsnhcRWZy/u9DHAMwaZOvk3Fy5+3JrX4T3YC4IANswyfP1sBqeSX+2G0x1RJ2hwTi3/P5NUD4NCq6Shg5UUy3CzGlAJWZe4kFddKWaOx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
