apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgBhS+X2DDWaeCDqhDKS0Apx3bB7pT8umZzkxgrZ9BKu+YQ94SFvxL42V43DVxRjT3nlbwduJZBlUogiOLffwaGTgitqdAMiZdZqRMBtbid0Dqw/6GmPHlTPBmAM8k8ahRF2V9IiTIRQhgYNnSwY+Qi+onknr6WTVSWLAanA0FEiVCu2Zj3K91cRq8yG3L8TbzvXRmUJKtQoVJu0q4rrqKy5jMLnztToXXW+4uHEh0QO7/fyXGTJ4iJffuiHXucAnpm9ztoiPqN4eI+2R+YlVaWPYsyABz+12waq/PkeH2m/A2YaTBhtw28wnpmmzs0jUO5bERnUoXGwqPmYcKObYixWCrrMk9Ia7atcvK+cAiDOk9qfBv9RenVY/P1rOURNFyZnKH7qx0NaRCitQ7xNTCpouD2kCn0DsdA+XiwBxolICIhODabqbq7rlONDs39CW3k/GJgAxqBtJ806Z7A+kxdKv8KqtWjypVUS6vcd+uP8lB/jylk10M/0kVkm+y8p3BFkjeU+Eb3neiYRtgO26dU+fpz86VxU4Wz8e6yLm7BKOo7bUnZHOeH7OQfFlK29Js90pxEbRT/L2WCx3jKZlj/dYkdl9U8XmvoCy+BUlc6bMe76BgIl2alwmkKh1qDFEEg3d0qosFPEG6Dvytizg66BtBZxBf9ylI9Got2XUYf8sOexXnLkiHtwq7AWM4gkyRGUAvs/lwWFxDKZ43cLJLDdUqsPYbsY2uxX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

